esite/app/urls.py
from django.urls import path     
from . import views
import sys
from django.conf import settings
from django.conf.urls.static import static

sys.path.append('../esite')

app_name = 'app'
urlpatterns = [
    # Page Section:
    path('', views.index, name='home'),
    path('registration', views.registration, name='registration'),
    path('products', views.products, name='products'),
    path('new_product_page', views.new_product_page, name='new_product_page'),                      
    path('edit_product_page/<int:product_id>', views.edit_product_page, name='edit_product_page'),                      


    # Process Section
    path('reg_process', views.reg_process, name='reg_process'),                      
    path('login_process', views.login_process, name='login_process'),                      
    path('logout_process', views.logout_process, name='logout_process'),                      
    path('new_product_process', views.new_product_process, name='new_product_process'),                      
    path('delete_product_process/<int:product_id>', views.delete_product_process, name='delete_product_process'),                      
    path('edit_product_process/<int:product_id>', views.edit_product_process, name='edit_product_process'),                      
    path('new_cat_process/', views.new_cat_process, name='new_cat_process'),                      

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

esite/esite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

esite/app/templates/article.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<main class="product-article">
    <div class="row ">
        <div class="col-sm-4 border text-center "><img src="{% static 'img/products/100.jpg' %}" id="product-image"
                class="product-image" alt="..."></div>
        <div class="col-sm-8 border ">
            <article class="product-article">
                <h3>Product Name</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor laboriosam vitae eos, dolores
                    voluptate magnam nemo dolorem ipsa vel architecto neque illo natus maiores nobis odio sint repellat
                    qui ducimus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis et impedit
                    assumenda eaque quod accusantium eligendi totam? Porro et expedita veritatis magnam illum eum
                    excepturi quos libero unde corrupti a nobis iusto in ipsa quae impedit eveniet animi odit possimus,
                    hic asperiores? Ex ab error voluptatum aspernatur, officiis molestiae commodi.</p>

            </article>
        </div>
    </div>
</main>

esite/app/templates/cat_modal.html
<div class="modal fade " id="cat_modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog mt-d">
        <div class="modal-content">
            <!-- Header Section of the Modal -->
            <div class="modal-header">
                <h5 class="modal-title"> Add Category</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Body Section of the Modal -->
                <form action="{% url 'app:new_cat_process' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <!-- Label Section -->
                        <div class="col-sm-4">
                            <label for="" class="form-label"> Category Name:</label>
                        </div>
                        <!-- Input Section -->
                        <div class="col-sm-6">
                            <input type="text" name="cat_name" class="form-control">
                        </div>
                    </div>

            </div>
            <!-- Footer Section of the Modal -->
            <div class="modal-footer">
                <button type="submit" class="btn btn-warning">Submit</button>
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
        </form>
    </div>
</div>

esite/app/templates/cat_modal_edit.html
<div class="modal fade " id="cat_modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog mt-d">
        <div class="modal-content">
            <!-- Header Section of the Modal -->
            <div class="modal-header">
                <h5 class="modal-title"> Add Category</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Body Section of the Modal -->
                <form action="{% url 'app:new_cat_process' %}" method="post">
                    <input type="hidden" name="page_source" value="edit_product_page">
                    <input type="hidden" name="product_id" value="{{product.id}}">
                    {% csrf_token %}
                    <div class="row">
                        <!-- Label Section -->
                        <div class="col-sm-4">
                            <label for="" class="form-label"> Category Name:</label>
                        </div>
                        <!-- Input Section -->
                        <div class="col-sm-6">
                            <input type="text" name="cat_name" class="form-control">
                        </div>
                    </div>

            </div>
            <!-- Footer Section of the Modal -->
            <div class="modal-footer">
                <button type="submit" class="btn btn-warning">Submit</button>
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
        </form>
    </div>
</div>

esite/app/templates/edit_product.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PalSika Edit Product</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

    {% include 'navbar.html' %}
    {% if user_session %}
    <div class="container pb-2 mb-3 pt-2 shadow main-margin-top" style="background-color: rgb(255, 255, 255);">
        <h1 class="text-center mb-5">Edit Product </h1>
        <!-- Category Modal -->
        {% include 'cat_modal_edit.html' %}
        <!-- Validation Messages -->
        {% include 'messages.html' %}
        <form action="{% url 'app:edit_product_process' product_id=product.id %}" method="post"
            enctype="multipart/form-data">
            {% csrf_token %}
            <!-- Product Name Section -->
            <div class="row mb-4 ">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Product Name:<span class="text-danger fs-5">*</span></label>
                </div>
                <div class="col-sm-5">
                    <input type="text" name="product_name" class="form-control" value="{{product.product_name}}" required>
                </div>
            </div>
            <!-- Product Category Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Product Category: <span class="text-danger fs-5">*</span> </label>
                </div>
                <div class="col-sm-3 d-flex align-items-center">
                    <select class="form-select" name="product_category" id="" required>
                        <option selected value="{{product.categories.id}}">{{product.categories.cat_name}}</option>
                        {% for cat in categories %}
                        <option value="{{cat.id}}">{{cat.cat_name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-sm-1 ">
                    <button type="button" class="btn-circle " data-bs-toggle="modal" data-bs-target="#cat_modal"><i
                            class="bi bi-plus-lg fs-2 fw-bold cat_icon "></i></button>

                </div>
            </div>
            <!-- product_qty Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Product Quantity:</label>
                </div>
                <div class="col-sm-5">
                    <input type="number" name="product_qty" class="form-control" value="{{product.product_qty}}">
                </div>
            </div>
            <!-- product_barcode Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Product Barcode:</label>
                </div>
                <div class="col-sm-5">
                    <input type="number" name="product_barcode" class="form-control"
                        value="{{product.product_barcode}}">
                </div>
            </div>
            <!-- product_desc Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Product Description:</label>
                </div>
                <div class="col-sm-5">
                    <textarea name="product_desc" class="form-control" rows="5">{{product.product_desc}}</textarea>
                </div>
            </div>
            <!-- Image Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Upload Image: <span class="text-danger fs-5">*</span></label>
                </div>
                <div class="col-sm-5">
                    <input type="file" name="product_image" class="form-control-file" value="{{product.product_image}}" required>
                </div>
            </div>
            <!-- Edit Button -->
            <div class="row mb-5 mt-5">
                <div class="col-sm-10  mx-auto">
                    <div class="d-grid col-3 mx-auto">
                        <button type="submit" class="btn btn-warning fs-5 fw-bold">Edit Product</button>
                    </div>

                </div>
            </div>
        </form>
    </div>
    {% else %}
    <h1 class="text-center text-danger" style="margin-top: 5rem;">Only Registered Users Can Have Access to this Page
    </h1>
    {% endif %}
    {% include 'footer.html' %}
</body>
<!-- Modal Section -->
<div id="my_modal" class="my_modal">
    <div class="loginFlex">
        <div class="modal_content glass">

            <hr>
            {% include 'login.html' %}

        </div>
    </div>


</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
<script src="{% static 'Js/script.js' %}"></script>

</html>

esite/app/templates/login.html
<main>
    <div class="loginContainer">
        <form action="{% url 'app:login_process' %}" method="post" class="text-center">
            {% csrf_token %}
            <!-- Add the 'X' button -->
            <div class="row justify-content-end ">
                <div class="col-sm-1 ">
                    <span class="  fs-2 pointer close"><strong>&times;</strong></span>
                </div>
                
            </div>
            <!-- Login Title -->
            <div class="row">
                <h1 class="text-white">Login</h1>
            </div>
            <hr class="border border-1 border-warning">
            <!-- Email Address Section -->
            <div class="row">
                <div class="col-sm-12 mb-3">
                    <label for="" class="form-label text-warning fs-3 ">Email Address:</label>
                    <input type="email" name="email" class="form-control">
                </div>
            </div>
            <!-- Password Section -->
            <div class="row">
                <div class="col-sm-12 mb-3">
                    <label for="" class="form-label text-warning fs-3 ">Password:</label>
                    <input type="password" name="password" class="form-control">
                </div>
            </div>
            <!-- Login Submit Button Section -->
            <div class="row">
                <div class="col-sm-12 mt-3 mb-3">
                    <button type="submit" class="btn btn-warning btn-lg "><strong>Login</strong></button>
                </div>
            </div>
        </form>
        <hr class="border border-1 border-black">
        <!-- Don't Have an Account Section -->
        <div class="row mb-3 justify-content-center">
            <div class="col-sm-12 text-center">
                <a href="{% url 'app:registration' %}" class="text-decoration-none text-warning">Don't have account ?</a>
            </div>
        </div>
    </div>
</main>

esite/app/templates/messages.html
<!-- Validation Messages -->
{% if messages %}
{% for message in messages %}
{% if message.tags == 'success' %}
<div class="alert alert-success alert-dismissible fade show" id="alert" role="alert">
    <strong>Success:</strong> {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
{% if message.tags == 'error' %}
<div class="alert alert-warning alert-dismissible fade show" id="alert" role="alert">
    <strong>Error:</strong> {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
{% endfor %}
{% endif %}

esite/app/templates/navbar.html
{% load static %}
<!-- Navbar  -->
<nav class="navbar navbar-expand-sm navbar-light bg-warning  shadow fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand mt-2" href="#"><img class="" style="width: 4rem; height: 4rem;" src="{% static 'img/sikalolo_trans.png' %}" alt="icon"> PalSika</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
            aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Items in the Navbar -->
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll fs-4" style="--bs-scroll-height: 100px;">
                <!-- Item -->
                <li class="nav-item">
                    <a class="nav-link active  {{selection.home}}" text-data="Home" aria-current="page" href="{% url 'app:home' %}">Home</a>
                </li>
                <!-- Item -->
                <li class="nav-item">
                    <a class="nav-link  active {{selection.products}}" aria-current="page"  text-data="Products" href="{% url 'app:products' %}" aria-disabled="true">Products</a>
                </li>
                <!-- Item -->
                <li class="nav-item">
                    <a class="nav-link disabled {{selection.contact_us}}" href="#" tabindex="-1"  text-data="Contact Us" aria-disabled="true">Contact Us</a>
                </li>
            </ul>
            <!-- Login Item -->
            <ul class="navbar-nav justify-content-end fs-4">
                {% if user_session  %}
                <li><a href="{% url 'app:logout_process' %}" id="logoutButton" class="text-dark pointer text-decoration-none">
                    
                    Welcome, {{user_session.first_name}} {{user_session.last_name}} 
                    <i class="bi bi-box-arrow-right" title="Logout"></i>
                </a></li>
                        
                        {% else %}
                        <li><span id="loginButton" class="text-dark pointer">
                            <img src="" alt="">
                            <i class="bi bi-people-fill"></i>
                            Login
                        </span></li>
                        {% endif %}

            </ul>
            <!-- Search Item  -->
            <!-- <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form> -->
        </div>
    </div>
</nav>

esite/app/templates/new_product.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PalSika Add New Product</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

    {% include 'navbar.html' %}
    {% if user_session %}
    <div class="container pb-2 mb-3 pt-2 shadow main-margin-top" style="background-color: rgb(255, 255, 255);">
        <h1 class="text-center mb-5">Add New Product </h1>
        <!-- Category Modal -->
        {% include 'cat_modal.html' %}
        <!-- Validation Messages -->
        {% include 'messages.html' %}
        <form action="{% url 'app:new_product_process' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- Product Name Section -->
            <div class="row mb-4 ">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Product Name:<span class="text-danger fs-5">*</span></label>
                </div>
                <div class="col-sm-5">
                    <input type="text" name="product_name" class="form-control" required>
                </div>
            </div>
            <!-- Product Category Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Product Category: <span class="text-danger fs-5">*</span> </label>
                </div>
                <div class="col-sm-3 d-flex align-items-center">
                    <select class="form-select" name="product_category" id="" required>
                        <option selected>Please Select a Category</option>
                        {% for cat in categories %}
                        <option value="{{cat.id}}" >{{cat.cat_name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-sm-1 ">
                    <button type="button" class="btn-circle " data-bs-toggle="modal" data-bs-target="#cat_modal"><i
                            class="bi bi-plus-lg fs-2 fw-bold cat_icon "></i></button>

                </div>
            </div>
            <!-- product_qty Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Product Quantity:</label>
                </div>
                <div class="col-sm-5">
                    <input type="number" name="product_qty" class="form-control">
                </div>
            </div>
            <!-- product_barcode Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Product Barcode:</label>
                </div>
                <div class="col-sm-5">
                    <input type="number" name="product_barcode" class="form-control">
                </div>
            </div>
            <!-- product_desc Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Product Description:</label>
                </div>
                <div class="col-sm-5">
                    <textarea name="product_desc" class="form-control" rows="5">Description part</textarea>
                </div>
            </div>
            <!-- Image Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Upload Image: <span class="text-danger fs-5">*</span></label>
                </div>
                <div class="col-sm-5">
                    <input type="file" name="product_image" value="no_image" class="form-control-file" required>
                </div>
            </div>
            <!-- Registration Button -->
            <div class="row mb-5 mt-5">
                <div class="col-sm-10  mx-auto">
                    <div class="d-grid col-3 mx-auto">
                        <button type="submit" class="btn btn-warning fs-5 fw-bold">Add Product</button>
                    </div>

                </div>
            </div>
        </form>
    </div>
    {% else %}
    <h1 class="text-center text-danger" style="margin-top: 5rem;">Only Registered Users Can Have Access to this Page
    </h1>
    {% endif %}
    {% include 'footer.html' %}
</body>
<!-- Modal Section -->
<div id="my_modal" class="my_modal">
    <div class="loginFlex">
        <div class="modal_content glass">

            <hr>
            {% include 'login.html' %}

        </div>
    </div>


</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
<script src="{% static 'Js/script.js' %}"></script>

</html>

esite/app/templates/product_obj.html
{% load static %}
<div class="col-sm-3">
    <div class="card d-flex align-items-center shadow " style="width: 18rem;">
        <img src="{% static 'img/products/100.jpg' %}" class="card-img-top "
            style="width: 10rem; height: 15rem;" alt="...">
        <div class="card-body">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk
                of the card's content.</p>
        </div>
    </div>
</div>

esite/app/templates/product_obj_admin.html
{% load static %}
<div class="col">
    <div class=" card d-flex align-items-center shadow position-relative mx-auto " style=" width: 18rem;">
        <!-- Image -->
        {% if product.product_image %}
        <img src="{{product.product_image.url}}" class="card-img-top p-5 product-image " alt="{{product.product_image}}">
        <div class="card-body  w-100">
            <h4 class=" title-h" >{{product.product_name}}</h4>
            <p class="card-text overflow-auto scrollbar" id="style-6" style="height: 6rem;">{{product.product_desc}}</p>
        </div>
        {% else %}
        <img src="{% static 'img/products/100.jpg' %}" class="card-img-top p-5 " alt="...">
        <div class="card-body  w-100">
            <h4 class=" title-h" >{{product.product_name}}</h4>
            <p class="card-text overflow-auto scrollbar" id="style-6" style="height: 6rem;">{{product.product_desc}}</p>
        </div>
        {% endif %}
        {% if user_session %}
        <!-- Edit and Delete buttons for admins -->
        <div class="position-absolute  top-0 end-0 ">
            <div class="d-flex flex-column  ">
                <!-- Delete Section -->
                <div class="mb-6 fs-4 scale">
                    <a href="{% url 'app:delete_product_process' product_id=product.id %}"><i
                            class="bi bi-circle-fill  text-danger position-absolute translate-middle fs-1"></i>
                        <i class="bi bi-trash3-fill text-white position-absolute translate-middle "></i>
                    </a>
                </div>
                <!-- Edit Section -->
                <div class="fs-4 scale">
                    <a href="{% url 'app:edit_product_page' product_id=product.id %}">
                        <i class="bi bi-circle-fill text-warning position-absolute translate-middle fs-1"></i>
                        <i class="bi bi-pencil position-absolute translate-middle text-dark"></i>
                    </a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>

</div>

esite/app/templates/products.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PalSika Products</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>


    {% include 'navbar.html' %}
    <div class="container  mb-3 p-3 shadow main-margin-top d-flex justify-content-center" 
        style="background-color: rgb(255, 255, 255);">
        <main class="mt-5  w-100 " >
            <!-- Check if Session exists -->
            {% if user_session %}
            <!-- Add New Product Button -->
            <div class="row mb-5 ">
                <div class="col-sm-10  mx-auto">
                    <div class="d-grid col-3 mx-auto">
                        <a href="{% url 'app:new_product_page' %}"
                            class="btn btn-warning fs-5 fw-bold shadow-sm border border-3 border-dark">Add New
                            Product</a>
                    </div>
                </div>
            </div>
            <hr class="border border-1 border-dark mb-5">
            {% endif %}
                    <!-- Validation Messages -->
        {% include 'messages.html' %}
            <div class="container  d-flex justify-content-center" >
                <div class="row row-cols-4 gy-4 w-100 " >
                    <!-- Display all products in the DB -->

                        {% for product in products %}
                        {% include 'product_obj_admin.html' %}
                        {% endfor %}
                </div>
            </div>
        </main>
    </div>
    {% include 'footer.html' %}
</body>
<!-- Modal Section -->
<div id="my_modal" class="my_modal">
    <div class="loginFlex">
        <div class="modal_content glass">

            <hr>
            {% include 'login.html' %}

        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
<script src="{% static 'Js/script.js' %}">
</script>

</html>

esite/app/templates/registration.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PalSika Registration Page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container pb-2 mb-3 pt-2 shadow main-margin-top" style="background-color: rgb(255, 255, 255);">
        <h1 class="text-center mb-5">Registration </h1>
        <!-- Error Validation Messages -->
{% include 'messages.html' %}

        <form action="{% url 'app:reg_process' %}" method="post">
            {% csrf_token %}
            <!-- First Name Section -->
            <div class="row mb-4 ">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> First Name:</label>
                </div>
                <div class="col-sm-5">
                    <input type="text" name="first_name" class="form-control">
                </div>
            </div>
            <!-- Last Name Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Last Name:</label>
                </div>
                <div class="col-sm-5">
                    <input type="text" name="last_name" class="form-control">
                </div>
            </div>
            <!-- email address Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Email Address:</label>
                </div>
                <div class="col-sm-5">
                    <input type="email" name="email" class="form-control">
                </div>
            </div>
            <!-- Password Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Password:</label>
                </div>
                <div class="col-sm-5">
                    <input type="password" name="password" class="form-control">
                </div>
            </div>
            <!-- Password Confirmation Section -->
            <div class="row mb-4">
                <div class="col-sm-4 text-center fs-4 fw-bold">
                    <label for="" class="form-label"> Confirm Password:</label>
                </div>
                <div class="col-sm-5">
                    <input type="password" name="password_confirmation" class="form-control">
                </div>
            </div>
            <!-- Registration Button -->
            <div class="row mb-5 mt-5">
                <div class="col-sm-10  mx-auto">
                    <div class="d-grid col-3 mx-auto">
                        <button type="submit" class="btn btn-warning fs-5 fw-bold">Register</button>
                    </div>

                </div>
            </div>
        </form>
    </div>

    {% include 'footer.html' %}
</body>
<!-- Modal Section -->
<div id="my_modal" class="my_modal">
    <div class="loginFlex">
        <div class="modal_content glass">

            <hr>
            {% include 'login.html' %}

        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
<script src="{% static 'Js/script.js' %}">
</script>

</html>